### ISSUE TITLE
fix - 스웨거 정상화

### ISSUE THREAD

**Issue by kseysh** [Team-HMH/HMH-Server#139]
## What is this issue? 🚀
스웨거가 안돼요..
<img width="1546" alt="image" src="https://github.com/Team-HMH/HMH-Server/assets/69035864/0c5527ac-6abf-40e4-8984-895e563a71bf">

## TODO 🏃‍♀️
- [ ] 스웨거 정상화

**Comment by jumining** [comment]
local에서는 되네요..

**Comment by kseysh** [comment]
아 그러면 https 적용안해서 그럴수도..!!!
