### ISSUE TITLE
feat - 포인트 모두 받기 api 구현

### ISSUE THREAD

**Issue by jumining** [Team-HMH/HMH-Server#144]
## What is this issue? 🚀
포인트뷰 오른쪽 상단 모두 받기 api 구현

## TODO 🏃‍♀️
- [ ] 모두 받기 api 구현

**Comment by kseysh** [comment]
앗 이거 하기로 했었나요??
그 의진이가 광고 추가할 수도 있어서 안하기로 했던 것으로 기억나는데... 가물가물...

**Comment by jumining** [comment]
그런가요...까먹이슈일까요 피그마 다시 살펴보다가 화면에 있길래 이슈 추가해뒀는데 1차 스프린트가 아니라면 추후 구현하도록 하겠슴다
