### ISSUE TITLE
chore - server error 발생 시 slack 연동

### ISSUE THREAD

**Issue by jumining** [Team-HMH/HMH-Server#160]
## What is this issue? 🚀
서버 에러시 슬랙으로 메시지 오게 만들기

## TODO 🏃‍♀️
- [ ] 슬랙 연동

**Comment by kseysh** [comment]
다른 페이지로 [이 내용](https://hmhteamhq.slack.com/archives/C06B6FGMPJL/p1719242547882809)도 같이 작업 부탁드리고 싶은데 괜찮을까요?
