### ISSUE TITLE
feat - Challenge 관련 Swagger 설정

### ISSUE THREAD

**Issue by jumining** [Team-HMH/HMH-Server#67]
## What is this issue? 🚀
주민이 작업한 api에 swagger 애노테이션을 연결하겠습니다.

## TODO 🏃‍♀️
- [ ] 애노테이션 연결
- [ ] 테스트

**Comment by kseysh** [comment]
interface에서 swagger를 설정할 수 있는 방법이 있다고 합니다! 그 부분 확인해서 사용하신다면 controller 코드를 좀 더 깔끔하게 유지할 수 있을 것 같아요!

**Comment by jumining** [comment]
https://velog.io/@yigongil201/Swagger-%EC%A0%81%EC%9A%A9%EA%B8%B0
